# Generated by Django 3.0.3 on 2020-03-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]
