# Generated by Django 3.0.3 on 2020-02-27 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cares',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clothes',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'main_categories',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_type', models.CharField(max_length=45)),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.MainCategory')),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
        migrations.CreateModel(
            name='ClothesSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.Clothes')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.Size')),
            ],
            options={
                'db_table': 'clothes_sizes',
            },
        ),
        migrations.CreateModel(
            name='ClothesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500)),
                ('clothes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.Clothes')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.Color')),
            ],
            options={
                'db_table': 'clothes_image',
            },
        ),
        migrations.CreateModel(
            name='ClothesColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.Clothes')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.Color')),
            ],
            options={
                'db_table': 'clothes_colors',
            },
        ),
        migrations.CreateModel(
            name='ClothesCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.Care')),
                ('clothes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.Clothes')),
            ],
            options={
                'db_table': 'clothes_cares',
            },
        ),
        migrations.AddField(
            model_name='clothes',
            name='care',
            field=models.ManyToManyField(through='clothes.ClothesCare', to='clothes.Care'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.ManyToManyField(through='clothes.ClothesColor', to='clothes.Color'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.MainCategory'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.ManyToManyField(through='clothes.ClothesSize', to='clothes.Size'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.SubCategory'),
        ),
    ]
