# Generated by Django 3.0.3 on 2020-03-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesimage',
            name='image1',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='clothesimage',
            name='image2',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='clothesimage',
            name='image3',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='clothesimage',
            name='image4',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='clothesimage',
            name='image5',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='clothesimage',
            name='image6',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='clothesimage',
            name='image7',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
