# Generated by Django 3.0.3 on 2020-02-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clothes',
            name='composition',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='clothes',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
