# Generated by Django 3.0.3 on 2020-03-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20200302_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
